import { AbilityConstant, ConfigurationConstant, UIAbility, Want } from '@kit.AbilityKit';
import { window } from '@kit.ArkUI';
import { logger } from '../utils/Logger';
import { common } from '@kit.AbilityKit';
import { QueryMessage } from '../abilityprovider/AbilityTypes';
import { GeneralAbilityManager } from '../abilityprovider/GeneralAbilityManager';

const TAG = 'EntryAbility';

export let globalContext: common.UIAbilityContext;

export let testFunc = (): Promise<void> => {
  EntryAbility.getInstance()?.test();
  return;
}

export default class EntryAbility extends UIAbility {
  private static instance: EntryAbility | null = null;

  public static getInstance(): EntryAbility | null {
    return EntryAbility.instance;
  }

  async onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): Promise<void> {
    logger.info(TAG, 'Ability onCreate');
    globalContext = this.context;
    EntryAbility.instance = this;
    try {
      this.context.getApplicationContext().setColorMode(ConfigurationConstant.ColorMode.COLOR_MODE_NOT_SET);
    } catch (err) {
      logger.error(TAG, `Failed to set colorMode. Cause: ${JSON.stringify(err)}`);
    }

    this.test().catch((error: Error) => {
      logger.error(TAG, `camera->mail demo error: ${JSON.stringify(error)}`);
    });
  }

  public async test() {
    const cameraQuery: QueryMessage = {
      header: {
        namespace: 'Camera',
        name: 'pick'
      },
      payload: {
        args: {
          type: 'PHOTO',
          cameraPosition: 'BACK'
        }
      }
    };
    logger.info(TAG, 'start camera->mail demo flow');
    const cameraResult = await GeneralAbilityManager.getInstance().handleQueryMessage(cameraQuery);
    logger.info(TAG, `camera result: ${JSON.stringify(cameraResult)}`);
    if (!cameraResult.success) {
      logger.error(TAG, `camera flow failed: ${JSON.stringify(cameraResult)}`);
      return;
    }
    const resultUri = cameraResult.outputs?.resultUri;
    if (typeof resultUri !== 'string' || resultUri.length === 0) {
      logger.error(TAG, 'camera flow failed: resultUri is empty');
      return;
    }
    const mailQuery: QueryMessage = {
      header: {
        namespace: 'Mail',
        name: 'send'
      },
      payload: {
        args: {
          sceneType: 1,
          email: ['xxx@example.com'],
          subject: 'WorkflowCelia Demo Photo',
          body: 'This mail is generated by Camera to Mail demo flow.',
          streamUris: [resultUri]
        }
      }
    };
    const mailResult = await GeneralAbilityManager.getInstance().handleQueryMessage(mailQuery);
    logger.info(TAG, `mail result: ${JSON.stringify(mailResult)}`);
  }

  onDestroy(): void {
    logger.info(TAG, 'Ability onDestroy');
  }

  onWindowStageCreate(windowStage: window.WindowStage): void {
    // Main window is created, set main page for this ability
    logger.info(TAG, 'Ability onWindowStageCreate');

    windowStage.loadContent('pages/Index', (err) => {
      if (err.code) {
        logger.error(TAG, `Failed to load the content. Cause: ${JSON.stringify(err)}`);
        return;
      }
      logger.info(TAG, 'Succeeded in loading the content.');
    });
  }

  onWindowStageDestroy(): void {
    // Main window is destroyed, release UI related resources
    logger.info(TAG, 'Ability onWindowStageDestroy');
  }

  onForeground(): void {
    // Ability has brought to foreground
    logger.info(TAG, 'Ability onForeground');
  }

  onBackground(): void {
    // Ability has back to background
    logger.info(TAG, 'Ability onBackground');
  }
}
